#!/bin/bash
echo landing...
echo ""
echo ""
echo "                                              ,o88888 "
echo "                                           ,o8888888' "
echo "                     ,:o:o:oooo.        ,8O88Pd8888"  
echo "                  ,.::.::o:ooooOoOoO. ,oO8O8Pd888'"   
echo "               ,.:.::o:ooOoOoOO8O8OOo.8OOPd8O8O" 
echo "              , ..:.::o:ooOoOOOO8OOOOo.FdO8O8" 
echo "             , ..:.::o:ooOoOO8O888O8O,COCOO" 
echo "            , . ..:.::o:ooOoOOOO8OOOOCOCO" 
echo "             . ..:.::o:ooOoOoOO8O8OCCCC'o "
echo "                . ..:.::o:ooooOoCoCCC'o:o "
echo "                . ..:.::o:o:,cooooCo'oo:o: "
echo "             .   . . ..:.:cocoooo''o:o:::. "
echo "             .'   . ..::ccccoc'o:o:o:::' "
echo "            :.:.    ,c:cccc'':.:.:.:.:.' "
echo "          ..:.:''\::::o:\\..:.:.:.:.:.\      "
echo "        ...:.'.:.::::''    . . . . .' "
echo "       .. . ....:.'' '   .  . . '' "
echo "     . . . ....'' "
echo "     .. . .''     "
echo "    . "

